# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/attention',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/attention',
                'lib_path': 'attention'},
  'syms': {'attention.core': {'attention.core.foo': ('core.html#foo', 'attention/core.py')}}}